---
title: "CAI Negotiation Assignment - Group 33 Final Report"
author: "Group 33"
date: "`r Sys.Date()`"
output:
  pdf_document:
    keep_tex: true
    number_sections: true
  word_document: default
  html_document:
    df_print: paged
bibliography: citations.bib
header-includes:
- \pdfpagewidth=8.5in
- \pdfpageheight=11in
- \usepackage{times}
- \usepackage{ijcai25}
- \usepackage{soul}
- \usepackage{url}
- \usepackage[hidelinks]{hyperref}
- \usepackage[utf8]{inputenc}
- \usepackage[small]{caption}
- \usepackage{graphicx}
- \usepackage{amsmath}
- \usepackage{amsthm}
- \usepackage{booktabs}
- \usepackage{algorithm}
- \usepackage{algorithmic}
- \usepackage[switch]{lineno}
- \urlstyle{same}
editor_options:
  markdown:
    wrap: 72
---

\tableofcontents

\vspace{2em}

\begin{abstract}

  This report describes a novel implementation of an autonomous agent
  for bilateral negotiation using a DANS opponent model and
  optimized acceptance criteria.

\end{abstract}

# Introduction

Multi-agent negotiation is a task for artificially intelligent and
autonomous systems that involves consensus decision-making. This report
focuses on bilateral negotiations between two agents supporting SAOP,
the Stacked Alternating Offers Protocol [@saop].

# Design

Our agent's goal is optimization of its individual utility. To do this,
iot must make competitive bids and concede minimally, finding the
highest-utility bid that the opponent will also accept. A key part of
this is identifying the opponent's strategy.

To accomplish this, our agent is designed around a BOA architecture
[@baarslag]. Its architecture is composed of the bidding strategy,
opponent model, and acceptance strategy as three high-level modules. BOA
was chosen because it excels in flexibility, allowing us to create a
more effective agent by combining innovations to each of its parts. This
section will describe them in sequence.

## Baseline opponent model

If the negotiation domain $\Omega$ is said to contain all possible
offers $\omega \in \Omega$, the agent already knows its own utility
function $u_m: \Omega \to \mathbb{R}$ and thus also the utility
$u_m(\omega)$ for all such offers. However, the opponent's function
$u_o: \Omega \to \mathbb{R}$ and values $u_o(\omega)$ are unknown. As
defined by @baarslag, the principle of the opponent model is to predict
$u_o(\omega)$.

Our agent utilizes the development template for ANAC 2023, which
implements a statistical opponent model. The `IssueEstimator` and
`ValueEstimator` classes are part of the `TemplateAgent`, and their
functionality will not be discussed here in detail. The implementation
uses frequency of received bids to provide an estimator
$\hat u_o: \Omega \to \mathbb{R}$ for the opponent's utility. The
implementation supports linear additive utility spaces only.

## DANS extended opponent model

As an extension of the provided estimator $\hat u_o$, we use DANS
analysis to identify the opponent's behavior based on the bid history.
DANS is a data-driven approach that uses the opponent's bid change
between consecutive time steps to classify bidding behavior.

The process assigns a category verdict to each bid based on the current
and previous time step. In doing this, DANS considers only the
opponent's offers. First, take the last two offers in the opponent's bid
history $B_o$:

$$
\omega_i, ~\omega_{i-1} ~~~ \text{where} ~~~ B_o = \{..., ~\omega_{i-1}, ~\omega_{i}\} 
$$

Next, define the two values to be used in classifying the behavior:

-   $\Delta m$ for change in our agent's utility:

    $$
    \Delta m = u_s(\omega_{i}) - u_s(\omega_{i-1}) 
    $$

-   $\Delta o$ for change in the opponent agent's utility (using the
    estimator):

    $$
    \Delta o = \hat u_o(\omega_{i}) - \hat u_o(\omega_{i-1}) 
    $$

Using thresholds on these values, one class is selected from the
following five: $\text{FORTUNATE}$, $\text{UNFORTUNATE}$,
$\text{SELFISH}$, $\text{NICE}$, and $\text{SILENT}$. These describe the
likely cause of the opponent's bid. The time-series history of DANS
classes is then used in the bidding and acceptance strategy to decide on
the best next action, such as by judging the dominant characteristic of
the opponent. We consider this data an extension of the opponent model,
as it serves to inform the decision-making process.

## Bidding strategy

@faratin propose two approaches to the question of bidding: time-based,
where the agent concedes more as the deadline approaches, and
behavior-based, where each bid is a response to opponent behavior.

Our bidding strategy combines the two, making use of all available
information.\

# Implementation

The agent was implemented in Python 3.9 and is fully compatible with the
GeniusWeb capabilities in use for the Automated Negotiating Agents
Competition (ANAC) 2023 and Automated Negotiation League (ANL) 2023. All
contributions by the authors of this report are extensions of the
`TemplateAgent` package in the ANL 2023 example agent repository[^1] by
Bram Renting and collaborators. This section describes the structure of
our implementation and corresponding methods in the source code.

[^1]: <https://github.com/brenting/ANL-2023-example-agent>

## Implementation of the DANS model

## Implementation of the bidding strategy

## Implementation of the acceptance strategy

# Optimization

The implementation of our agent includes 'tuning' parameters. We
leverage Bayesian optimization to find an optimum value for each
parameter based on testing with a set of known agents.

# Evaluation

The final stage of our optimization procedure is the source of data for
our evaluation. We run the agent against a cross product of 50 test
agents and 5 randomly selected preference domains. The data that results
from this testing is discussed in this chapter as an indicator of our
agent's performance and limitations.

## Performance against other agents

The data should indicate that we perform well for individual utility
against a variety of opponent agents.

## Limitations

### Learning agents

The data suggests good performance in one-shot learning agents. However,
the evaluation does not consider advanced learning agents that could
presumably gain an advantage over a number of 'training' runs against
our implementation.

# Conclusion

In conclusion, we have shown that a DANS-based opponent model is a
viable strategy for autonomous negotiation.

# Ethical Statement {.unnumbered}

While there are no ethical issues with the design and implementation of
our autonomous agent, @agent-ethics writes that such issues may arise
when self-serving negotiation agents such as ours are applied in
sensitive contexts.

# Acknowledgments {.unnumbered}

We acknowledge the support and instruction of Carolina Jorge, Ruben
Verhagen, Myrthe Tielman, and Pradeep K. Murukannaiah of Interactive
Intelligence at Delft University of Technology. We thank the Teaching
Assistants.

# Work distribution {.unnumbered}

Group 33 distributed the work equally.

# References {.unnumbered}
