---
title: "CAI Negotiation Assignment - Report on \"Results\" folder"
author: "Group 33"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    keep_tex: yes
    number_sections: yes
header-includes:
  - \usepackage{times}
  - \usepackage{ijcai25}
---

\tableofcontents

# About

This document contains all runs in the Results folder of the repository.

```{r setup, echo=FALSE}
source("aana_utils.R")
```

```{r, echo=TRUE}
repo_path <- "../cai-anl-33/"
```

```{r, echo=FALSE}
results_dir <- paste(repo_path, 'results/', sep='')
results_dir_listing <- dir(results_dir)
cat(file=stderr(), sprintf("\nResults directory: %d entries\n", length(results_dir_listing)))

git_rev <- substr(system2(c("git", "-C", repo_path, "reflog"), stdout=TRUE), 1, 7)
cat(file=stderr(), sprintf("\nGit revision '%s'\n", git_rev))
```

```{r, results="asis", echo=FALSE, warning=FALSE, message=FALSE, fig.height=5.1, fig.width=6, fig.align='center'}

cat(sprintf("Git repository at \\verb|%s|, version \\verb|%s|.", repo_path, git_rev))

for (results in results_dir_listing) {

  cat(sprintf("\n\\clearpage\n\n# Results at %s\n", results))
  
  result_data <- try(
    read_results(results_dir, results)
  )
  if (inherits(result_data, "try-error")) {
    next;
  } else {
    plot_run_results(result_data)
  }
}
```
